- hosts:
    - aorus
    - gigabyte
  tasks:
    - name: execute sampling
      shell: cd /home/tomas/CLionProjects/muzero/cmake-build-release && ulimit -n 4096 && ./muzero --workers {{workers}} --num_selfplay {{selfplay}} --batch {{batch}} --executors {{executors}} > /tmp/sampling.out

- hosts: aorus
  tasks:
    - name: train
      shell: cd /home/tomas/CLionProjects/muzero/cmake-build-release && ./muzero --train true --lr 0.01 --window 36864 --batch 16 --checkpoint 100 --training_steps 6001 >> /tmp/training.out