- hosts:
    - aorus
    - gigabyte
  tasks:
    - name: execute sampling
      shell: cd /home/tomas/CLionProjects/muzero/cmake-build-release && ./muzero --workers {{workers}} --num_selfplay 12 > /tmp/sampling.out

- hosts: aorus
  tasks:
    - name: train
      shell: cd /home/tomas/CLionProjects/muzero/cmake-build-release && ./muzero --train true --lr 0.01 --window 10000 --batch 64 --checkpoint 100 --training_steps 101 > /tmp/training.out